---
- name: Desktop provisioning
  hosts: all
  roles:
    - common
    - audio
    - communication
    - develop
    - gui
    - network
    - photo
    - user
    - utils
    - video
    - web
    - dotfiles
